name: Build application (Windows)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: "beta"
          flutter-version: "3.7.0-1.5.pre"
          cache: true
      - name: Build release
        run: script/build_windows.bat
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Better-MCFallout-Bot-${{ inputs.version }}-Windows
          path: ${{ github.workspace }}/app/build/windows/runner/Release
