name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        type: string
        required: true
      body:
        description: "Release body"
        type: string
        required: false

jobs:
  build_linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      version: ${{ github.event.inputs.version }}
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      version: ${{ github.event.inputs.version }}
  build_macos:
    uses: ./.github/workflows/build_macos.yml
    with:
      version: ${{ github.event.inputs.version }}

  release:
    needs:
      - build_linux
      - build_windows
      - build_macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download files
        uses: actions/download-artifact@v3

      - name: Zip Linux
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "Better-MCFallout-Bot-${{ github.event.inputs.version }}-Linux.zip"
          path: Better-MCFallout-Bot-${{ github.event.inputs.version }}-Linux
      - name: Zip Windows
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: "Better-MCFallout-Bot-${{ github.event.inputs.version }}-Windows.zip"
          path: Better-MCFallout-Bot-${{ github.event.inputs.version }}-Windows

      - name: Release files
        uses: softprops/action-gh-release@v1
        with:
          name: Better MCFallout Bot ${{ github.event.inputs.version }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.body }}
          files: |
            Better-MCFallout-Bot-${{ github.event.inputs.version }}-Linux.zip
            Better-MCFallout-Bot-${{ github.event.inputs.version }}-Windows.zip
            Better-MCFallout-Bot-${{ github.event.inputs.version }}-macOS/Better-MCFallout-Bot-${{ github.event.inputs.version }}-macOS.dmg
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.event.inputs.version }}
